SELECT * FROM Categoria;
SELECT * FROM Produto;

INSERT INTO Produto(Nome, Descricao, QtdeEstoque, ValorCusto, ValorVenda, Destaque, CategoriaId) VALUES
('Camisa 1 24/25', 'O uniforme 1 24/25 � verde com detalhes em branco, destacando o escudo do clube no peito. Possui design moderno e confort�vel, com tecnologia para garantir desempenho e respirabilidade.', 50, 200.00, 399.90, 1, 1),
('Camisa 2 24/25', 'O uniforme 2 24/25 � branco com detalhes em verde, destacando o escudo do clube no peito. Possui design moderno e confort�vel, com tecnologia para garantir desempenho e respirabilidade.', 60, 180.00, 349.99, 1, 1),
('Camisa 3 24/25', 'O uniforme 3 24/25 � dourado com detalhes em verde, destacando o escudo do clube no peito. Possui design moderno e confort�vel, com tecnologia para garantir desempenho e respirabilidade.', 40, 250.00, 499.90, 1, 1),
('Camisa Goleiro 1 24/25', 'O uniforme 1 de goleiro 24/25 � azul com listras em um tom mais claro de azul, destacando o escudo do clube no peito. Possui design moderno e confort�vel, com tecnologia para garantir desempenho e respirabilidade.', 30, 150.00, 299.99, 0, 1),
('Camisa 1 25/26', 'O uniforme 1 25/26 � verde com detalhes em branco, destacando o escudo do clube no peito. Possui design moderno e confort�vel, com tecnologia para garantir desempenho e respirabilidade.', 70, 240.00, 499.99, 1, 1),
('Camisa 2 25/26', 'O uniforme 2 25/26 � branco com as mangas em verde, destacando o escudo do clube no peito. Possui design moderno e confort�vel, com tecnologia para garantir desempenho e respirabilidade.', 65, 240.00, 499.99, 1, 1),
('Camisa Goleiro 1 25/26', 'O uniforme 1 de goleiro 25/26 � azul claro com detalhes em um tom de azul mais escuro, destacando o escudo do clube no peito. Possui design moderno e confort�vel, com tecnologia para garantir desempenho e respirabilidade.', 50, 240.00, 499.99, 0, 1),
('Camisa Treino e Viagem 24/25', 'A camisa de treino � verde lim�o com detalhes em verde escuro, destacando o escudo do clube no peito. Possui design moderno e confort�vel, com tecnologia para garantir desempenho e respirabilidade.', 80, 150.00, 279.90, 0, 2),
('Jaqueta Treino 24/25', 'A jaqueta de treino � azul com detalhes em um tom de azul mais escuro, destacando o escudo do clube no peito. Possui design moderno e confort�vel, com tecnologia para garantir desempenho e respirabilidade.', 25, 500.00, 949.99, 1, 2),
('Camisa Motorsport', 'A camiseta Motorsport traz um design moderno e arrojado, com detalhes que combinam estilo e performance. Inspirada no universo das competi��es automobil�sticas, ela une a tradi��o do clube � energia do esporte a motor.', 40, 200.00, 399.99, 1, 3),
('Camisa Football', 'A camiseta Football � inspirada no estilo do futebol americano, com um design robusto e detalhes marcantes. Ela mistura a identidade do clube com a est�tica das ligas norte-americanas, trazendo um toque esportivo e moderno.', 90, 80.00, 159.90, 0, 3),
('Regata Basket Palestra', 'A camisa regata Basket � inspirada no basquete, com um design urbano e esportivo. Com detalhes que lembram a est�tica das quadras, ela combina estilo e praticidade, sendo perfeita para os f�s do clube e do esporte.', 70, 100.00, 169.99, 0, 3),
('Polo Treino 22/23', 'A camisa polo de treino 22/23, na cor azul, traz um design sofisticado e moderno, com detalhes sutis que valorizam a identidade do clube. Ideal para quem busca um estilo casual e elegante, ela une conforto e tradi��o de forma discreta e refinada.', 100, 70.00, 149.99, 0, 4),
('Polo Viagem 20/21', 'A camisa polo de viagem 20/21 apresenta um design elegante e confort�vel, ideal para os momentos de deslocamento dos jogadores. Com detalhes em verde e o escudo do clube, ela combina estilo casual com a tradi��o alviverde.', 50, 150.00, 249.90, 0, 4),
('Polo Casual 24/25', 'A camisa polo casual 24/25 combina sofistica��o e descontra��o, com um design moderno e detalhes que refletem a identidade do clube. Perfeita para ocasi�es casuais, ela traz o estilo cl�ssico da polo com um toque contempor�neo, ideal para os torcedores alviverdes.', 60, 200.00, 349.90, 1, 4);

INSERT INTO ProdutoFoto (ProdutoId, Foto, Descricao) VALUES
(1, 'C:\Users\Alunobcc06\Desktop\Giovanna\loja-grigo\LojaGrigo\wwwroot\img\produtos\Uniforme de Jogo\Camisa1F.webp', 'Foto da frente'),
(1, 'C:\Users\Alunobcc06\Desktop\Giovanna\loja-grigo\LojaGrigo\wwwroot\img\produtos\Uniforme de Jogo\Camisa1T.webp', 'Foto de tr�s'),
(2, 'C:\Users\Alunobcc06\Desktop\Giovanna\loja-grigo\LojaGrigo\wwwroot\img\produtos\Uniforme de Jogo\Camisa2F.png', 'Foto da frente'),
(2, 'C:\Users\Alunobcc06\Desktop\Giovanna\loja-grigo\LojaGrigo\wwwroot\img\produtos\Uniforme de Jogo\Camisa2T.webp', 'Foto de tr�s'),
(3, 'C:\Users\Alunobcc06\Desktop\Giovanna\loja-grigo\LojaGrigo\wwwroot\img\produtos\Uniforme de Jogo\Camisa3F.webp', 'Foto da frente'),
(3, 'C:\Users\Alunobcc06\Desktop\Giovanna\loja-grigo\LojaGrigo\wwwroot\img\produtos\Uniforme de Jogo\Camisa3T.webp', 'Foto de tr�s'),
(4, 'C:\Users\Alunobcc06\Desktop\Giovanna\loja-grigo\LojaGrigo\wwwroot\img\produtos\Uniforme de Jogo\Goleiro1F.webp', 'Foto da frente'),
(4, 'C:\Users\Alunobcc06\Desktop\Giovanna\loja-grigo\LojaGrigo\wwwroot\img\produtos\Uniforme de Jogo\Goleiro1T.webp', 'Foto de tr�s'),
(5, 'C:\Users\Alunobcc06\Desktop\Giovanna\loja-grigo\LojaGrigo\wwwroot\img\produtos\Uniforme de Jogo\Camisa25F.png', 'Foto da frente'),
(5, 'C:\Users\Alunobcc06\Desktop\Giovanna\loja-grigo\LojaGrigo\wwwroot\img\produtos\Uniforme de Jogo\Camisa25T.png', 'Foto de tr�s'),
(6, 'C:\Users\Alunobcc06\Desktop\Giovanna\loja-grigo\LojaGrigo\wwwroot\img\produtos\Uniforme de Jogo\2Camisa25F.png', 'Foto da frente'),
(6, 'C:\Users\Alunobcc06\Desktop\Giovanna\loja-grigo\LojaGrigo\wwwroot\img\produtos\Uniforme de Jogo\2Camisa25T.png', 'Foto de tr�s'),
(7, 'C:\Users\Alunobcc06\Desktop\Giovanna\loja-grigo\LojaGrigo\wwwroot\img\produtos\Uniforme de Jogo\GK25F.png', 'Foto da frente'),
(7, 'C:\Users\Alunobcc06\Desktop\Giovanna\loja-grigo\LojaGrigo\wwwroot\img\produtos\Uniforme de Jogo\GK25T.png', 'Foto de tr�s'),
(8, 'C:\Users\Alunobcc06\Desktop\Giovanna\loja-grigo\LojaGrigo\wwwroot\img\produtos\Treino e Viagem\CamisaTreinoF.webp', 'Foto da frente'),
(8, 'C:\Users\Alunobcc06\Desktop\Giovanna\loja-grigo\LojaGrigo\wwwroot\img\produtos\Treino e Viagem\CamisaTreinoT.webp', 'Foto de tr�s'),
(9, 'C:\Users\Alunobcc06\Desktop\Giovanna\loja-grigo\LojaGrigo\wwwroot\img\produtos\Treino e Viagem\JaquetaTreino.png', null),
(10, 'C:\Users\Alunobcc06\Desktop\Giovanna\loja-grigo\LojaGrigo\wwwroot\img\produtos\Linha Torcedor\Motorsport.webp', null),
(11, 'C:\Users\Alunobcc06\Desktop\Giovanna\loja-grigo\LojaGrigo\wwwroot\img\produtos\Linha Torcedor\FootballF.webp', 'Foto da frente'),
(11, 'C:\Users\Alunobcc06\Desktop\Giovanna\loja-grigo\LojaGrigo\wwwroot\img\produtos\Linha Torcedor\FootballT.webp', 'Foto de tr�s'),
(12, 'C:\Users\Alunobcc06\Desktop\Giovanna\loja-grigo\LojaGrigo\wwwroot\img\produtos\Linha Torcedor\RegataF.webp', 'Foto da frente'),
(12, 'C:\Users\Alunobcc06\Desktop\Giovanna\loja-grigo\LojaGrigo\wwwroot\img\produtos\Linha Torcedor\RegataT.webp', 'Foto de tr�s'),
(13, 'C:\Users\Alunobcc06\Desktop\Giovanna\loja-grigo\LojaGrigo\wwwroot\img\produtos\Polos\PoloTreinoF.png', 'Foto da frente'),
(13, 'C:\Users\Alunobcc06\Desktop\Giovanna\loja-grigo\LojaGrigo\wwwroot\img\produtos\Polos\PoloTreinoT.png', 'Foto de tr�s'),
(14, 'C:\Users\Alunobcc06\Desktop\Giovanna\loja-grigo\LojaGrigo\wwwroot\img\produtos\Polos\PoloViagemF.webp', 'Foto da frente'),
(14, 'C:\Users\Alunobcc06\Desktop\Giovanna\loja-grigo\LojaGrigo\wwwroot\img\produtos\Polos\PoloViagemT.webp', 'Foto de tr�s'),
(15, 'C:\Users\Alunobcc06\Desktop\Giovanna\loja-grigo\LojaGrigo\wwwroot\img\produtos\Polos\PoloCasualF.png', 'Foto da frente'),
(15, 'C:\Users\Alunobcc06\Desktop\Giovanna\loja-grigo\LojaGrigo\wwwroot\img\produtos\Polos\PoloCasualT.webp', 'Foto de tr�s');